### ISSUE TITLE
BE - Integrate Aura with Exposure API

### ISSUE THREAD

**Issue by ca-pikachu** [vish1406/exchange-node#346]
Aura docs for [Exposure API](https://documenter.getpostman.com/view/1457658/SVtVVTzY?version=latest#c46f75f9-81c4-4c17-bfa0-6869e34bafb5)

Acceptance Criteria:
- [x] Save User Bets from Aura to our DB
- [x] Ensure the `exposure`, `balance`, `userPl` and other similar data is properly updated
- [x] Store other data received from Aura request in `metaData`
- [x] Add common bet validations for 
- user exist
- token
- user bet limits (exposure, balance, pl, ...)
- other ...

Dev notes:
- Create separate `auraBetService.js` in `services/v1/bet`
- For other validations and code flow refer `placeBetService.js`
- If you don't get the running pls for this type of bet from the existing functions in `betPlService.js` then create similar functions for getting the running pl in `auraBetService.js`

**Comment by nihangrethinksoft** [comment]
1. How can I get market information
2. How we calculate possible win and loss
3. Calculated exposure is bet exposure?
